In [1]:
import tweepy
import json
import pandas as pd
import random

In [3]:
consumer_key = 'oasBl5z8gOK7Q3PNoiOiqLZNs'
consumer_key_secret = 'blmLWYnC5omThauKWSx95FR35U8hiBxS1gp81jXApWd3OtX9oF'
access_token = '1272637484577353728-Ik68xPgo7SkXpx7dCqmbIscIHZmUAX'
access_token_secret = 'HjAOZWg87IwukA35zIHipG74TK8A1ITbsl8uVo7TH7Yhb'

In [4]:
auth = tweepy.OAuthHandler(consumer_key, consumer_key_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

In [31]:
text = []
time = []
category = []
location = []

In [217]:
api = tweepy.API(auth)
#made a cursor
c = tweepy.Cursor(api.search, q='cyber crime india')
c.pages(5000) # you can change it make get tweets

#Lets save the selected part 
# x = []
for tweet in c.items():
    text.append(tweet._json['text'])
    time.append(tweet._json['created_at'])
    location.append(tweet._json['location'])
    category.append('cyber crime')

In [220]:
len(text), len(time), len(category), len(location)

(18495, 18495, 18495, 18495)

In [226]:
df = pd.DataFrame(list(zip(text,category,time,location)),columns=['Text','Category','Time','Location'])
df

,Text,Category,Time,Location
0,RT @boltaup: बलात्कार के मामलों में दूसरे नंबर...,rape,Fri Sep 17 02:04:25 +0000 2021,Punjab
1,RT @nevans1984: Why Ransomware Hackers Love Ho...,theft,Fri Sep 10 09:55:15 +0000 2021,Chhattisgarh
2,20 years old BSC RADIOLOGY Student from #Budga...,murder,Mon Sep 13 08:47:47 +0000 2021,Maharashtra
3,Among India's metro cities with over 20 lakh p...,murder,Fri Sep 17 06:13:13 +0000 2021,Bihar
4,RT @KairaMorgan: I marched for the sister I lo...,rape,Thu Sep 16 14:56:20 +0000 2021,Haryana
...,...,...,...,...
18490,RT @boltaup: बलात्कार के मामलों में दूसरे नंबर...,rape,Thu Sep 16 09:54:20 +0000 2021,Madhya Pradesh
18491,RT @meetgoogle: @SunitaNandwani3 औरत वह बनो जो...,rape,Sat Sep 18 04:31:31 +0000 2021,Kerala
18492,RT @punjabkesari: साल 2020 में देश में साइबर क...,cyber crime,Thu Sep 16 17:43:45 +0000 2021,Karnataka
18493,Why Ransomware Hackers Love Holidays Analytic...,theft,Fri Sep 10 09:55:03 +0000 2021,Rajasthan
18494,Why Ransomware Hackers Love Holidays Analytic...,theft,Fri Sep 10 09:55:03 +0000 2021,Maharashtra

In [227]:
df.to_csv("data.csv")

In [7]:
df = pd.read_csv('data.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df= df.sample(frac = 1)
df.reset_index(inplace=True)
df.drop(columns=['index'], inplace=True)
df

,Text,Category,Time,Location
0,RT @ZeeNewsCrime: भाई बहन के रिश्ते को शर्मसार...,murder,Sun Sep 12 02:49:58 +0000 2021,Assam
1,"RT @the_hindu: #India recorded 50,035 cases of...",cyber crime,Wed Sep 15 16:18:30 +0000 2021,Karnataka
2,RT @nsvirk: In case you find your data has be ...,cyber crime,Sun Sep 12 21:47:59 +0000 2021,Andhra Pradesh
3,@heena41039319 @cyber_c_india @Uppolice @deepa...,cyber crime,Sat Sep 18 06:54:07 +0000 2021,Jharkhand
4,India is the worst country in the world to g...,murder,Sun Sep 12 15:01:48 +0000 2021,Rajasthan
...,...,...,...,...
18490,RT @CBhoomia: Cyber Crime &amp; Fake News Rise...,cyber crime,Fri Sep 17 16:41:54 +0000 2021,Odisha
18491,A 24-year-old former national level Kho-Kho pl...,murder,Sun Sep 12 04:35:55 +0000 2021,Meghalaya
18492,Damn Texas. You're no good at controlling the...,rape,Tue Sep 14 22:22:57 +0000 2021,Maharashtra
18493,RT @Cyberdost: Beware of cyber crime and repo...,cyber crime,Thu Sep 16 05:56:10 +0000 2021,Delhi
18494,RT @RachakondaCop: ఎవరైనా #సైదాబాద్ చిన్నారి హ...,rape,Wed Sep 15 00:00:49 +0000 2021,Chhattisgarh